# Document Topic Distribution

In [2]:
import pandas as pd
import numpy as np

num_topics = 26
df = pd.read_csv(f"~/Desktop/R_js/data/gamma/pro{num_topics}_gamma.csv")
df['log_gamma'] = np.absolute(np.log(df.gamma))
display(df.head())
print(df.shape)

   document  topic     gamma  log_gamma
0         1      1  0.007911   4.839471
1         2      1  0.015577   4.161986
2         3      1  0.012643   4.370688
3         4      1  0.013582   4.299036
4         5      1  0.015417   4.172280

(874120, 4)

In [3]:
lst = []
for t in range(1, num_topics+1): 
    df_topic = df[df.topic == t]
    lst.append(df_topic.gamma.sum())

tot = sum(lst)
lst = np.array([i/tot for i in lst])

print((lst).argsort()[::-1] + 1)


lst[::-1].sort()
print(lst)
print(sum(lst))

[ 7 22  9  3  2 21 25 18 16 10 15 11 12 24  5 23 20  8 13  6  4 17 19 14
  1 26]
[0.09793896 0.06855978 0.06467575 0.05493386 0.05381987 0.05317543
 0.05276865 0.04398549 0.04293406 0.04288514 0.04170761 0.03423775
 0.03336776 0.03127346 0.03112398 0.03055929 0.02968621 0.02873513
 0.02436143 0.0242779  0.02287956 0.0210971  0.0203284  0.01802537
 0.01695286 0.0157092 ]
1.0

In [14]:
a = sum(df[df.topic == 1].gamma.tolist())
print(a)

569.9551795260503

# Topic Term Distribution

In [33]:
df = pd.read_csv(f"~/Desktop/R_js/data/beta/pro{num_topics}_beta.csv")
display(df.head())
tot_term = df[df.topic == 1]['term'].count()
print(tot_term)

   topic          term           beta
0      1  1_hour_break  3.672673e-208
1      2  1_hour_break  1.351000e-189
2      3  1_hour_break  8.675901e-213
3      4  1_hour_break  4.690151e-197
4      5  1_hour_break  6.897081e-192

6641

In [90]:
terms = df[df.topic == 1]["term"].values.tolist()
lst = []
i = 1
for t in terms: 
    term_prob = df[df.term == t]['beta'].sum()/num_topics
    lst.append([i, t, term_prob])
    i = i+1
df_term = pd.DataFrame(lst, columns=['word_id', 'word', 'word_prob'])
display(df_term.head())

   word_id                 word  word_prob
0        1         1_hour_break   0.000008
1        2         1_hour_lunch   0.000700
2        3           1_hr_lunch   0.000091
3        4     10_discount_card   0.000015
4        5  10_discount_flexibl   0.000008

In [91]:


for t in terms: 
    term_prob = df_term.loc[df_term.word == t, "word_prob"].iloc[0]
    df.loc[df.term == t, "word_prob"] = term_prob

In [4]:
lam = .5
df["term_freq"] = tot_term*df.word_prob
df["relevance"] = lam*df.beta + (1-lam)*df.beta/df.word_prob

NameError: name 'tot_term' is not defined

In [93]:
display(df.head())

   topic          term           beta      relevance      term_freq  word_prob
0      1  1_hour_break  3.672673e-208  2.225913e-203  2.439022e-204   0.000008
1      2  1_hour_break  1.351000e-189  8.188065e-185  8.971991e-186   0.000008
2      3  1_hour_break  8.675901e-213  5.258241e-208  5.761666e-209   0.000008
3      4  1_hour_break  4.690151e-197  2.842581e-192  3.114729e-193   0.000008
4      5  1_hour_break  6.897081e-192  4.180144e-187  4.580352e-188   0.000008

In [94]:
df24 = df[df.topic == 25]
df24.sort_values(by="relevance", ascending=False)

,topic,term,beta,relevance,term_freq,word_prob
144012,25,schedul,1.261088e-01,1.306305e+01,8.374885e+02,0.004850
58810,25,excel,1.215417e-01,1.306077e+01,8.071582e+02,0.004675
161796,25,train,1.027139e-01,1.305136e+01,6.821230e+02,0.003951
65856,25,flexibl_schedul,5.965235e-02,1.302983e+01,3.961513e+02,0.002294
83796,25,healthcar,5.117049e-02,1.302556e+01,3.398232e+02,0.001968
58888,25,excel_benefit,3.821479e-02,1.301911e+01,2.537844e+02,0.001470
118428,25,packag,3.569820e-02,1.301785e+01,2.370718e+02,0.001373
7798,25,awesom,3.262238e-02,1.301631e+01,2.166452e+02,0.001255
15728,25,benefit_packag,2.414056e-02,1.301207e+01,1.603175e+02,0.000928
96900,25,level,1.314216e-02,1.300657e+01,8.727708e+01,0.000505
161276,25,tool,8.668232e-03,1.300433e+01,5.756573e+01,0.000333
83874,25,healthcar_benefit,7.736164e-03,1.300387e+01,5.137587e+01,0.000298
144090,25,schedul_benefit,6.990510e-03,1.300350e+01,4.642398e+01,0.000269
18484,25,benefit_train,6.244856e-03,1.300312e+01,4.147209e+01,0.000240
13128,25,benefit_excel,5.592408e-03,1.300280e+01,3.713918e+01,0.000215
123498,25,pay_excel,5.405994e-03,1.300270e+01,3.590121e+01,0.000208
13492,25,benefit_flexibl_schedul,5.312788e-03,1.300266e+01,3.528222e+01,0.000204
56262,25,entri,4.939960e-03,1.300247e+01,3.280628e+01,0.000190
60084,25,excel_train,4.567133e-03,1.300228e+01,3.033033e+01,0.000176
90868,25,incom,4.007892e-03,1.300200e+01,2.661641e+01,0.000154
7850,25,awesom_benefit,3.821479e-03,1.300191e+01,2.537844e+01,0.000147
59148,25,excel_benefit_packag,3.541858e-03,1.300177e+01,2.352148e+01,0.000136
162628,25,train_program,3.541858e-03,1.300177e+01,2.352148e+01,0.000136
133066,25,possibl,3.448652e-03,1.300172e+01,2.290249e+01,0.000133
162524,25,train_opportun,3.262238e-03,1.300163e+01,2.166452e+01,0.000125
14142,25,benefit_healthcar,3.262238e-03,1.300163e+01,2.166452e+01,0.000125
144376,25,schedul_flexibl,3.169031e-03,1.300158e+01,2.104554e+01,0.000122
65882,25,flexibl_schedul_benefit,3.075824e-03,1.300154e+01,2.042655e+01,0.000118
59746,25,excel_manag,3.075824e-03,1.300154e+01,2.042655e+01,0.000118
116972,25,oppurtun,3.075824e-03,1.300154e+01,2.042655e+01,0.000118
...,...,...,...,...,...,...
156310,25,tea_soft_drink,8.857378e-253,1.234999e-247,5.882185e-249,0.000004
67442,25,food_free_fountain,2.174465e-253,2.021266e-248,1.444062e-249,0.000005
83562,25,health_dental_vision,7.958494e-253,8.117469e-249,5.285236e-249,0.000049
44822,25,dental_vision_benefit,1.158679e-254,2.954473e-250,7.694785e-251,0.000020
167698,25,vision_benefit,1.158679e-254,2.954473e-250,7.694785e-251,0.000020
135068,25,producto,0.000000e+00,0.000000e+00,0.000000e+00,0.000008
141490,25,revenu,0.000000e+00,0.000000e+00,0.000000e+00,0.000051
39986,25,creativ_freedom,0.000000e+00,0.000000e+00,0.000000e+00,0.000013
52076,25,dupont,0.000000e+00,0.000000e+00,0.000000e+00,0.000009
19914,25,bien,0.000000e+00,0.000000e+00,0.000000e+00,0.000017
111434,25,mucho,0.000000e+00,0.000000e+00,0.000000e+00,0.000012
135094,25,productt,0.000000e+00,0.000000e+00,0.000000e+00,0.000004
87384,25,horribl,0.000000e+00,0.000000e+00,0.000000e+00,0.000024
149394,25,smell,0.000000e+00,0.000000e+00,0.000000e+00,0.000009
80468,25,gran,0.000000e+00,0.000000e+00,0.000000e+00,0.000011
115594,25,oportunidad_de,0.000000e+00,0.000000e+00,0.000000e+00,0.000007
26024,25,cach,0.000000e+00,0.000000e+00,0.000000e+00,0.000009
168010,25,volunt_leav,0.000000e+00,0.000000e+00,0.000000e+00,0.000017
62398,25,fam,0.000000e+00,0.000000e+00,0.000000e+00,0.000013
2650,25,accident,0.000000e+00,0.000000e+00,0.000000e+00,0.000020
143466,25,salud,0.000000e+00,0.000000e+00,0.000000e+00,0.000016
163512,25,tree,0.000000e+00,0.000000e+00,0.000000e+00,0.000011
21058,25,bonu_pto,0.000000e+00,0.000000e+00,0.000000e+00,0.000012
152670,25,stereo,0.000000e+00,0.000000e+00,0.000000e+00,0.000008
79506,25,ge_name,0.000000e+00,0.000000e+00,0.000000e+00,0.000007
60656,25,exp,0.000000e+00,0.000000e+00,0.000000e+00,0.000007
148978,25,slight,0.000000e+00,0.000000e+00,0.000000e+00,0.000006
43080,25,day_vacat,0.000000e+00,0.000000e+00,0.000000e+00,0.000013
55404,25,empresa,0.000000e+00,0.000000e+00,0.000000e+00,0.000038
115568,25,oportunidad,0.000000e+00,0.000000e+00,0.000000e+00,0.000022

In [95]:
(df[df.term=="schedul"]["beta"].sum()) * tot_term

837.4885328210632

In [80]:
sum = 0
for t in terms: 
    sum += df[df.term == t]["beta"].sum()

In [81]:
print(sum)

25.999999999999883